// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calculateAutocovariance
arma::cube calculateAutocovariance(const arma::mat& X, const arma::mat& Y, const int& maxLag);
RcppExport SEXP _autocovarianceTesting_calculateAutocovariance(SEXP XSEXP, SEXP YSEXP, SEXP maxLagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxLag(maxLagSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateAutocovariance(X, Y, maxLag));
    return rcpp_result_gen;
END_RCPP
}
// calculateCovariance
Rcpp::List calculateCovariance(const arma::mat& X, const arma::mat& Y, const double& L, const int& trunc);
RcppExport SEXP _autocovarianceTesting_calculateCovariance(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP truncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type trunc(truncSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateCovariance(X, Y, L, trunc));
    return rcpp_result_gen;
END_RCPP
}
// calculateTestStat
Rcpp::List calculateTestStat(const arma::colvec& delta, const arma::mat& covar, const int& n, const int& L, const int& k, const arma::colvec weight);
RcppExport SEXP _autocovarianceTesting_calculateTestStat(SEXP deltaSEXP, SEXP covarSEXP, SEXP nSEXP, SEXP LSEXP, SEXP kSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateTestStat(delta, covar, n, L, k, weight));
    return rcpp_result_gen;
END_RCPP
}
// calculateBootTestStat
Rcpp::List calculateBootTestStat(const arma::mat& X, const arma::mat& Y, const double& L, int const& B, int const& b, bool const& prewhiten, int const& trunc, bool const& dependent_series);
RcppExport SEXP _autocovarianceTesting_calculateBootTestStat(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP BSEXP, SEXP bSEXP, SEXP prewhitenSEXP, SEXP truncSEXP, SEXP dependent_seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int const& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool const& >::type prewhiten(prewhitenSEXP);
    Rcpp::traits::input_parameter< int const& >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< bool const& >::type dependent_series(dependent_seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBootTestStat(X, Y, L, B, b, prewhiten, trunc, dependent_series));
    return rcpp_result_gen;
END_RCPP
}
// calculateBootTestStatJin
Rcpp::List calculateBootTestStatJin(const arma::mat& X, const arma::mat& Y, const double& L, int const& B, int const& b, bool const& prewhiten, int const& trunc);
RcppExport SEXP _autocovarianceTesting_calculateBootTestStatJin(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP BSEXP, SEXP bSEXP, SEXP prewhitenSEXP, SEXP truncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int const& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool const& >::type prewhiten(prewhitenSEXP);
    Rcpp::traits::input_parameter< int const& >::type trunc(truncSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBootTestStatJin(X, Y, L, B, b, prewhiten, trunc));
    return rcpp_result_gen;
END_RCPP
}
// calculateBootTestStatBartlett
Rcpp::List calculateBootTestStatBartlett(const arma::mat& X, const arma::mat& Y, const double& L, int const& B, int const& b, bool const& prewhiten, int const& trunc, bool const& dependent_series);
RcppExport SEXP _autocovarianceTesting_calculateBootTestStatBartlett(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP BSEXP, SEXP bSEXP, SEXP prewhitenSEXP, SEXP truncSEXP, SEXP dependent_seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int const& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool const& >::type prewhiten(prewhitenSEXP);
    Rcpp::traits::input_parameter< int const& >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< bool const& >::type dependent_series(dependent_seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBootTestStatBartlett(X, Y, L, B, b, prewhiten, trunc, dependent_series));
    return rcpp_result_gen;
END_RCPP
}
// calculateBootTestStatFixed
Rcpp::List calculateBootTestStatFixed(const arma::mat& X, const arma::mat& Y, const double& L, int const& B, int const& b, bool const& prewhiten, int const& trunc, bool const& dependent_series, const arma::colvec weight);
RcppExport SEXP _autocovarianceTesting_calculateBootTestStatFixed(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP BSEXP, SEXP bSEXP, SEXP prewhitenSEXP, SEXP truncSEXP, SEXP dependent_seriesSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int const& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool const& >::type prewhiten(prewhitenSEXP);
    Rcpp::traits::input_parameter< int const& >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< bool const& >::type dependent_series(dependent_seriesSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBootTestStatFixed(X, Y, L, B, b, prewhiten, trunc, dependent_series, weight));
    return rcpp_result_gen;
END_RCPP
}
// calculateBootTestStatFixedUnweighted
Rcpp::List calculateBootTestStatFixedUnweighted(const arma::mat& X, const arma::mat& Y, const double& L, int const& B, int const& b, bool const& prewhiten, int const& trunc, bool const& dependent_series, const arma::colvec weight);
RcppExport SEXP _autocovarianceTesting_calculateBootTestStatFixedUnweighted(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP BSEXP, SEXP bSEXP, SEXP prewhitenSEXP, SEXP truncSEXP, SEXP dependent_seriesSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int const& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool const& >::type prewhiten(prewhitenSEXP);
    Rcpp::traits::input_parameter< int const& >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< bool const& >::type dependent_series(dependent_seriesSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBootTestStatFixedUnweighted(X, Y, L, B, b, prewhiten, trunc, dependent_series, weight));
    return rcpp_result_gen;
END_RCPP
}
// calculateBootTestStatFixedWeighted
Rcpp::List calculateBootTestStatFixedWeighted(const arma::mat& X, const arma::mat& Y, const double& L, int const& B, int const& b, bool const& prewhiten, int const& trunc, bool const& dependent_series, const arma::colvec weight);
RcppExport SEXP _autocovarianceTesting_calculateBootTestStatFixedWeighted(SEXP XSEXP, SEXP YSEXP, SEXP LSEXP, SEXP BSEXP, SEXP bSEXP, SEXP prewhitenSEXP, SEXP truncSEXP, SEXP dependent_seriesSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int const& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool const& >::type prewhiten(prewhitenSEXP);
    Rcpp::traits::input_parameter< int const& >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< bool const& >::type dependent_series(dependent_seriesSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBootTestStatFixedWeighted(X, Y, L, B, b, prewhiten, trunc, dependent_series, weight));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_autocovarianceTesting_calculateAutocovariance", (DL_FUNC) &_autocovarianceTesting_calculateAutocovariance, 3},
    {"_autocovarianceTesting_calculateCovariance", (DL_FUNC) &_autocovarianceTesting_calculateCovariance, 4},
    {"_autocovarianceTesting_calculateTestStat", (DL_FUNC) &_autocovarianceTesting_calculateTestStat, 6},
    {"_autocovarianceTesting_calculateBootTestStat", (DL_FUNC) &_autocovarianceTesting_calculateBootTestStat, 8},
    {"_autocovarianceTesting_calculateBootTestStatJin", (DL_FUNC) &_autocovarianceTesting_calculateBootTestStatJin, 7},
    {"_autocovarianceTesting_calculateBootTestStatBartlett", (DL_FUNC) &_autocovarianceTesting_calculateBootTestStatBartlett, 8},
    {"_autocovarianceTesting_calculateBootTestStatFixed", (DL_FUNC) &_autocovarianceTesting_calculateBootTestStatFixed, 9},
    {"_autocovarianceTesting_calculateBootTestStatFixedUnweighted", (DL_FUNC) &_autocovarianceTesting_calculateBootTestStatFixedUnweighted, 9},
    {"_autocovarianceTesting_calculateBootTestStatFixedWeighted", (DL_FUNC) &_autocovarianceTesting_calculateBootTestStatFixedWeighted, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_autocovarianceTesting(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
