# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateAutocovariance <- function(X, Y, maxLag) {
    .Call(`_autocovarianceTesting_calculateAutocovariance`, X, Y, maxLag)
}

calculateCovariance <- function(X, Y, L, trunc) {
    .Call(`_autocovarianceTesting_calculateCovariance`, X, Y, L, trunc)
}

calculateTestStat <- function(delta, covar, n, L, k, weight) {
    .Call(`_autocovarianceTesting_calculateTestStat`, delta, covar, n, L, k, weight)
}

calculateBootTestStat <- function(X, Y, L, B, b, prewhiten, trunc, dependent_series) {
    .Call(`_autocovarianceTesting_calculateBootTestStat`, X, Y, L, B, b, prewhiten, trunc, dependent_series)
}

calculateBootTestStatJin <- function(X, Y, L, B, b, prewhiten, trunc) {
    .Call(`_autocovarianceTesting_calculateBootTestStatJin`, X, Y, L, B, b, prewhiten, trunc)
}

calculateBootTestStatBartlett <- function(X, Y, L, B, b, prewhiten, trunc, dependent_series) {
    .Call(`_autocovarianceTesting_calculateBootTestStatBartlett`, X, Y, L, B, b, prewhiten, trunc, dependent_series)
}

calculateBootTestStatFixed <- function(X, Y, L, B, b, prewhiten, trunc, dependent_series, weight) {
    .Call(`_autocovarianceTesting_calculateBootTestStatFixed`, X, Y, L, B, b, prewhiten, trunc, dependent_series, weight)
}

calculateBootTestStatFixedUnweighted <- function(X, Y, L, B, b, prewhiten, trunc, dependent_series, weight) {
    .Call(`_autocovarianceTesting_calculateBootTestStatFixedUnweighted`, X, Y, L, B, b, prewhiten, trunc, dependent_series, weight)
}

calculateBootTestStatFixedWeighted <- function(X, Y, L, B, b, prewhiten, trunc, dependent_series, weight) {
    .Call(`_autocovarianceTesting_calculateBootTestStatFixedWeighted`, X, Y, L, B, b, prewhiten, trunc, dependent_series, weight)
}

