# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute computes the DEMEANED autocovariance function of two concatenated multivariate time series
#' 
#' @param X a time series
#' @param Y a time series
#' @export
calculateAutocovariance <- function(X, Y, maxLag) {
    .Call(`_autocovarianceTesting_calculateAutocovariance`, X, Y, maxLag)
}

calculateCovariance <- function(X, Y, L) {
    .Call(`_autocovarianceTesting_calculateCovariance`, X, Y, L)
}

