# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateAutocovariance <- function(X, Y, maxLag) {
    .Call(`_autocovarianceTesting_calculateAutocovariance`, X, Y, maxLag)
}

calculateCovariance <- function(X, Y, L) {
    .Call(`_autocovarianceTesting_calculateCovariance`, X, Y, L)
}

calculateTestStat <- function(delta, covar, n, L, k) {
    .Call(`_autocovarianceTesting_calculateTestStat`, delta, covar, n, L, k)
}

calculateBootTestStat <- function(X, Y, L, B, b, prewhiten) {
    .Call(`_autocovarianceTesting_calculateBootTestStat`, X, Y, L, B, b, prewhiten)
}

